name: Validate README

on:
  push:

jobs:
  varify-action-inputs-table:
    name: Verify action inputs table is up to date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"

      - run: ./scripts/update-readme.sh
      - uses: tj-actions/verify-changed-files@v10.1
        id: verify-changed-files
        with:
          files: |
            README.md

      - name: Fail if README.md changed
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        run: |
          echo "README.md changed as a result of running `./scripts/update-readme.sh`"
          exit 1
